name: Motivation Auto Poster

on:
  schedule:
    # --- 4 Baar Post Karne Ka Schedule (UTC Time) ---
    
    # 1. Subah 9:00 AM IST (03:30 UTC)
    - cron: '30 3 * * *'
    
    # 2. Dopahar 1:00 PM IST (07:30 UTC)
    - cron: '30 7 * * *'
    
    # 3. Shaam 5:00 PM IST (11:30 UTC)
    - cron: '30 11 * * *'
    
    # 4. Raat 9:00 PM IST (15:30 UTC)
    - cron: '30 15 * * *'
  
  workflow_dispatch:      # Manual 'Run' button

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries (Direct Mode)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          
          # Yahan humne sidha libraries likh di hain taaki koi error na aaye
          pip install google-api-python-client google-auth-oauthlib google-auth-httplib2 requests moviepy==1.0.3 "numpy<2.0.0" instagrapi==1.17.0

      - name: Run Main Script
        env:
          G_CLIENT_ID: ${{ secrets.G_CLIENT_ID }}
          G_CLIENT_SECRET: ${{ secrets.G_CLIENT_SECRET }}
          G_REFRESH_TOKEN: ${{ secrets.G_REFRESH_TOKEN }}
          
          INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
          INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD }}
          INSTA_SESSION: ${{ secrets.INSTA_SESSION }}
          
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          DRIVE_DONE_ID: ${{ secrets.DRIVE_DONE_ID }}
        run: python main.py
